import { DragElement } from "src/app/interfaces/drag-element.interface";
import { environment } from "src/environments/environment";

const defaultStyle: any = {
    'fontSize.px': '14',
    color: '#212529',
    fontWeight: '400',
    'width.%': '100',
    'height.px': '22',
    align: 'left',
    background: '#ffffff',
    'borderRadius.px': '0',
    borderColor: '0',
    'paddingTop.px': '0',
    'paddingRight.px': '0',
    'paddingBottom.px': '0',
    'paddingLeft.px': '0',
    'marginTop.px': '5',
    'marginRight.px': '5',
    'marginBottom.px': '5',
    'marginLeft.px': '5',
};
const defaultParentStyle: any = {
    width: '100',
    justifyContent: 'left',
};

export const componentList: DragElement[] = [
  {
    title: 'Text',
    icon: `${environment.images}/pencil.svg`,
    tag: 'p',
    type: 'text',
    class: 'custom-text',
    value: 'Text',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Text Input',
    icon: `${environment.images}/toy-alphabet-blocks.svg`,
    tag: 'input',
    placeholder: 'Placeholer',
    type: 'text',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Textarea',
    icon: `${environment.images}/writing.svg`,
    tag: 'textarea',
    placeholder: 'Placeholer',
    type: 'text',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Checkbox',
    icon: `${environment.images}/checkbox.svg`,
    tag: 'input',
    type: 'checkbox',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Date',
    icon: `${environment.images}/date.svg`,
    tag: 'input',
    type: 'date',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Email',
    icon: `${environment.images}/email-round-solid.svg`,
    tag: 'input',
    placeholder: 'Placeholer',
    type: 'email',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Password',
    icon: `${environment.images}/password.svg`,
    tag: 'input',
    placeholder: 'Placeholer',
    type: 'password',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Number',
    icon: `${environment.images}/board-score.svg`,
    tag: 'input',
    placeholder: 'Placeholer',
    type: 'number',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Link',
    icon: `${environment.images}/domain-name.svg`,
    tag: 'input',
    placeholder: 'Placeholer',
    type: 'url',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Radio Button',
    icon: `${environment.images}/list-view.svg`,
    tag: 'input',
    placeholder: 'Placeholer',
    type: 'radio',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Multi Select',
    icon: `${environment.images}/select-all.svg`,
    tag: 'select',
    placeholder: 'Placeholer',
    type: 'text',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
    options: ['Option'],
  },
  {
    title: 'Select',
    icon: `${environment.images}/check-mark-box-line.svg`,
    tag: 'select',
    placeholder: 'Placeholer',
    type: 'text',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
    options: ['Option'],
  },
  {
    title: 'File Uploader',
    icon: `${environment.images}/file-upload.svg`,
    tag: 'input',
    placeholder: 'Placeholer',
    type: 'file',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Button',
    icon: `${environment.images}/submit-label.svg`,
    tag: 'button',
    placeholder: 'Placeholer',
    value: 'Submit',
    type: 'submit',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
];