import { ComponentTag } from "src/app/enums/component-tag.model";
import { InputType } from "src/app/enums/input-type.model";
import { DragElement } from "src/app/interfaces/drag-element.interface";
import { environment } from "src/environments/environment";

const defaultStyle: any = {
    'fontSize.px': '14',
    color: 'unset',
    fontWeight: '400',
    'width.%': '100',
    'height.px': '22',
    align: 'left',
    background: 'unset',
    'borderRadius.px': '0',
    borderColor: 'unset',
    'paddingTop.px': '0',
    'paddingRight.px': '0',
    'paddingBottom.px': '0',
    'paddingLeft.px': '0',
    'marginTop.px': '5',
    'marginRight.px': '5',
    'marginBottom.px': '5',
    'marginLeft.px': '5',
};
const defaultParentStyle: any = {
    width: '100',
    justifyContent: 'left',
};

export const componentList: DragElement[] = [
  {
    title: 'Text',
    icon: `${environment.images}/pencil.svg`,
    tag: ComponentTag.p,
    type: InputType.text,
    class: 'custom-text',
    value: 'Text',
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Text Input',
    icon: `${environment.images}/toy-alphabet-blocks.svg`,
    tag: ComponentTag.input,
    placeholder: 'Placeholer',
    type: InputType.text,
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Textarea',
    icon: `${environment.images}/writing.svg`,
    tag: ComponentTag.textarea,
    placeholder: 'Placeholer',
    type: InputType.text,
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Checkbox',
    icon: `${environment.images}/checkbox.svg`,
    tag: ComponentTag.input,
    type: InputType.checkbox,
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Date',
    icon: `${environment.images}/date.svg`,
    tag: ComponentTag.input,
    type: InputType.date,
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Email',
    icon: `${environment.images}/email-round-solid.svg`,
    tag: ComponentTag.input,
    placeholder: 'Placeholer',
    type: InputType.email,
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Password',
    icon: `${environment.images}/password.svg`,
    tag: ComponentTag.input,
    placeholder: 'Placeholer',
    type: InputType.password,
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Number',
    icon: `${environment.images}/board-score.svg`,
    tag: ComponentTag.input,
    placeholder: 'Placeholer',
    type: InputType.number,
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Link',
    icon: `${environment.images}/domain-name.svg`,
    tag: ComponentTag.input,
    placeholder: 'Placeholer',
    type: InputType.url,
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Radio Button',
    icon: `${environment.images}/list-view.svg`,
    tag: ComponentTag.input,
    placeholder: 'Placeholer',
    type: InputType.radio,
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Multi Select',
    icon: `${environment.images}/select-all.svg`,
    tag: ComponentTag.select,
    placeholder: 'Placeholer',
    type: InputType.text,
    style: defaultStyle,
    parentStyle: defaultParentStyle,
    options: ['Option'],
  },
  {
    title: 'Select',
    icon: `${environment.images}/check-mark-box-line.svg`,
    tag: ComponentTag.select,
    placeholder: 'Placeholer',
    type: InputType.text,
    style: defaultStyle,
    parentStyle: defaultParentStyle,
    options: ['Option'],
  },
  {
    title: 'File Uploader',
    icon: `${environment.images}/file-upload.svg`,
    tag: ComponentTag.input,
    placeholder: 'Placeholer',
    type: InputType.file,
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
  {
    title: 'Button',
    icon: `${environment.images}/submit-label.svg`,
    tag: ComponentTag.button,
    placeholder: 'Placeholer',
    value: 'Submit',
    type: InputType.submit,
    style: defaultStyle,
    parentStyle: defaultParentStyle,
  },
];