export enum InputType {
    button = 'BUTTON',
    checkbox = 'CHECKBOX',
    color = 'COLOR',
    date = 'DATE',
    email = 'EMAIL',
    file = 'FILE',
    hidden = 'HIDDEN',
    image = 'IMAGE',
    month = 'MONTH',
    number = 'NUMBER',
    password = 'PASSWORD',
    radio = 'RADIO',
    range = 'RANGE',
    reset = 'RESET',
    search = 'SEARCH',
    submit = 'SUBMIT',
    tel = 'TEL',
    text = 'TEXT',
    time = 'TIME',
    url = 'URL',
    week = 'WEEK',
}
